web/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from api import views

router = DefaultRouter()

router.register('ratings',views.RatingViewSet, basename='ratings')
router.register('products', views.ProductsViewSet, basename='products')

urlpatterns = [
    path('', include(router.urls))
]

web/cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'
urlpatterns = [
    path('', views.CartView.as_view(), name='detail'),
    path('add/<int:product_id>/', views.cart_add, name='add'),
    path('add-quick/<int:product_id>/', views.cart_add_quick,
         name='add-quick'),
    path('remove/<int:product_id>/', views.cart_remove, name='remove')
]

web/store/urls.py
from django.urls import path
from store import views

app_name = 'store'
urlpatterns = [
    path('', views.ProductListView.as_view(), name='productlist'),
    path('category/<str:slug>/', views.ProductCategoryListView.as_view(),
         name='productlist-by-category'),
    path('product/<str:slug>/', views.ProductDetailView.as_view(),
         name='product-detail'),
    path('wishlist/', views.WishListView.as_view(), name='wishlist'),
    path('recommendations/<int:user_id>/', views.RecommendationsView.as_view(),
         name='recommendations'),
    path('bestselling/', views.BestsellingView.as_view(), name='bestselling'),
    path('mostwished/', views.MostWishedView.as_view(), name='mostwished')
]

web/web/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('store.urls', namespace='store')),
    path('users/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payments/', include('payments.urls', namespace='payments'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/store/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.shortcuts import reverse


class Category(models.Model):
    """Category model."""

    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('store:productlist-by-category', args=[self.slug])


class Product(models.Model):
    """Product model."""

    category = models.ForeignKey(Category, related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('store:product-detail', args=[self.slug])

    def wished_by_users(self):
        users_q = self.product_wished.filter(product_id=self.id)
        user_list = [i.user_id for i in users_q]
        return user_list

    def get_rating(self):
        rating = 0
        ratings_q = self.product_rate.filter(product_id=self.id)
        all_rates = ratings_q.count()
        for i in ratings_q:
            rating += i.rate
        rating = rating / all_rates
        return rating

    def count_rates(self):
        count = self.product_rate.filter(product_id=self.id).count()
        return count


@receiver(post_delete, sender=Product)
def delete_image(sender, instance, **kwargs):
    """Delete uploaded image."""

    if instance.image:
        instance.image.delete(False)


class Wish(models.Model):
    """Wish model."""

    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='user_wish')
    product = models.ForeignKey(Product, on_delete=models.CASCADE,
                                related_name='product_wished')

    def __str__(self):
        return f'User: {self.user} liked product:{self.product}'

    def get_user_id(self):
        return self.user.id

    def get_product_id(self):
        return self.product.id


class Rating(models.Model):
    """Rating model."""

    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='user_rate')
    product = models.ForeignKey(Product, on_delete=models.CASCADE,
                                related_name='product_rate')
    rate = models.IntegerField()

    def __str__(self):
        return f'User {self.user} rated {self.product} with {self.rate}'

    def get_rate(self):
        return self.rate

web/store/forms.py
from django import forms
from store.models import Rating


class RatingForm(forms.Form):
    """Rating form"""

    rate = forms.IntegerField(label='', min_value= 0, max_value=5,
                              widget=forms.NumberInput(
                                  attrs={
                                      'class': 'rating-form__input',
                                      'placeholder':'0'
                                  }
                              ))

web/store/views.py
import json
import requests
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.views import View
from django.shortcuts import render, get_object_or_404, redirect
from cart.forms import CartAddButton, CartAddForm
from orders.models import OrderItem
from store.forms import RatingForm
from store.mixins import WishMixin
from store.models import Category, Product, Wish, Rating
from store.recommendations import Recommendations
from store.tasks import fit_model

recommendations_url = settings.RECOMMENDATIONS_URL
fit_url = settings.FIT_URL


class ProductListView(WishMixin, View):
    """Productlist view."""

    def get(self, request):
        categories = Category.objects.all()
        product_list = Product.objects.filter(available=True)
        paginator = Paginator(product_list, 6)
        page = request.GET.get('page')

        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)

        context = {
            'products': products,
            'categories': categories,
            'category': 'All categories'
        }
        return render(request, 'store/product_list.html', context)


class ProductCategoryListView(WishMixin, View):
    """Product list view by category."""

    def get(self, request, slug):
        categories = Category.objects.all()
        category = get_object_or_404(Category, slug=slug)
        product_list = Product.objects.filter(category=category)
        product_list = product_list.filter(available=True)
        paginator = Paginator(product_list, 6)
        page = request.GET.get('page')

        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)

        form = CartAddButton()
        context = {
            'products': products,
            'categories': categories,
            'category': category,
            'form': form
        }
        return render(request, 'store/product_list.html', context)


class ProductDetailView(View):
    """Product detail view."""

    r = Recommendations()

    def get(self, request, slug):
        product = get_object_or_404(Product, slug=slug)
        categories = Category.objects.all()

        form = CartAddForm()

        rating_form = RatingForm()

        recommended_products = self.r.suggest_products_for([product], 4)

        context = {
            'product': product,
            'categories': categories,
            'form': form,
            'rating_form': rating_form,
            'recommended_products': recommended_products
        }
        return render(request, 'store/product_detail.html', context)

    def post(self, request, slug):
        user = User.objects.get(id=request.user.id)
        product = Product.objects.get(slug=slug)
        rating_form = RatingForm(request.POST)

        if 'wish' in request.POST:
            product_id = request.POST.get('wish')
            Wish.objects.create(
                user=user,
                product_id=product_id
            )
        if 'del' in request.POST:
            product_id = request.POST.get('del')
            wishes = Wish.objects.filter(product_id=product_id)
            wish = wishes.filter(user_id=user.id)
            wish.delete()

        if rating_form.is_valid():
            rate = rating_form.cleaned_data.get('rate')
            try:
                ex_rate = Rating.objects.get(user=user, product=product)
            except ObjectDoesNotExist:
                ex_rate = None
            if ex_rate:
                ex_rate.rate = rate
                ex_rate.save()

                fit_model.delay()

            else:
                Rating.objects.create(
                    user=user,
                    product=product,
                    rate=rate
                )

                fit_model.delay()

        return redirect('store:product-detail', slug=slug)


class WishListView(LoginRequiredMixin, WishMixin, View):
    """Products wish list."""

    def get(self, request):
        categories = Category.objects.all()
        user = User.objects.get(id=request.user.id)
        wishes = Wish.objects.filter(user=user)
        wishes_id_list = [i.product_id for i in wishes]
        product_list = Product.objects.filter(id__in=wishes_id_list)
        paginator = Paginator(product_list, 6)
        page = request.GET.get('page')
        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)

        context = {
            'categories': categories,
            'products': products,
            'category': 'Wish list'
        }
        return render(request, 'store/product_list.html', context)


class RecommendationsView(LoginRequiredMixin, WishMixin, View):
    """Recommendations view makes post request with user_id and
    gets product id's."""

    def get(self, request, user_id):
        categories = Category.objects.all()
        user = User.objects.get(id=user_id)
        try:
            user_id = {'user_id': user.id}
            j = json.dumps(user_id)

            response = requests.post(recommendations_url, data=j)
            response = json.loads(response.json())

            rec_list = response['recommendations']
            products = []
            for i in rec_list:
                products.append(Product.objects.get(id=int(i)))

            context = {
                'categories': categories,
                'products': products,
                'category': 'Recommendations'
            }
        except json.JSONDecodeError:
            context = {
                'categories': categories,
                'products': [],
                'category': 'Recommendations'
            }
        except requests.exceptions.ConnectionError:
            context = {
                'categories': categories,
                'products': [],
                'category': 'Recommendations'
            }

        return render(request, 'store/product_list.html', context)


class BestsellingView(WishMixin, View):
    """Returns products sorted buy amount of purchases."""

    def get(self, request):
        categories = Category.objects.all()
        all_orders = OrderItem.objects.all()

        orders_dict = {}

        for item in all_orders:
            if item.product_id not in orders_dict.keys():
                orders_dict[item.product_id] = item.quantity
            else:
                orders_dict[item.product_id] += item.quantity
        orders_list_sorted = sorted(orders_dict,
                                    key=orders_dict.get, reverse=True)

        bestselling = []
        for i in orders_list_sorted[0:6]:
            bestselling.append(Product.objects.get(id=i))

        context = {
            'categories': categories,
            'products': bestselling,
            'category': 'Bestselling'
        }
        return render(request, 'store/product_list.html', context)


class MostWishedView(WishMixin, View):
    """Returns most wished products."""

    def get(self, request):
        categories = Category.objects.all()
        wishes = Wish.objects.all()

        wishes_dict = {}

        for item in wishes:
            if item.product_id not in wishes_dict.keys():
                wishes_dict[item.product_id] = 1
            else:
                wishes_dict[item.product_id] += 1

        wishes_list_sorted = sorted(wishes_dict,
                                    key=wishes_dict.get, reverse=True)
        most_wished = []
        for i in wishes_list_sorted[0:6]:
            most_wished.append(Product.objects.get(id=i))

        context = {
            'categories': categories,
            'products': most_wished,
            'category': 'Most wished'
        }
        return render(request, 'store/product_list.html', context)

web/store/templates/store/product_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock title %}
{% block content %}
<div class="row">
    <div class="col-3">
        {% include "components/_sidebar.html" %}
    </div>
    <div class="col-9">
        <div class="card-detail-wrapper">
            <div class="card-detail">
                <div class="card-detail__img">
                    <img src=" 
                    {% if product.image %}
                    {{ product.image.url }}
                    {% else %}
                    {% static 'icons/no-image.png' %}
                    {% endif %} " alt="">
                </div>
                <div class="card-detail__title">
                    <h4>{{ product.name }}</h4>
                </div>
                <div class="card-detail__price">
                    <h4>$ {{ product.price }}</h4>
                </div>
                <div class="card-detail__rating">
                    {% include "components/_rating.html" %}
                    <div class="card__rating-value">{{ product.count_rates }}</div>
                </div>
                {% if user.is_authenticated %}
                <div class="card-detail__rating-form">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="rating-form__input-wrapper">
                            {{ rating_form }}
                        </div>
                        <button type="submit" class="rating-form__input-btn">Rate</button>
                    </form>
                </div>
                <div class="card-detail__cart-form">
                    <form method="POST" action="{% url 'cart:add' product_id=product.id %}">
                        {% csrf_token %}
                        {{ form }}
                        <button class="card-form__input-btn">To cart</button>
                    </form>
                </div>
                <div class="card-detail__wish-form">
                    <form method="POST">
                        {% csrf_token %}
                        {% if user.id in product.wished_by_users %}
                        <button value="{{ product.id }}" name="del" class="wish-form__input-btn-del">Remove from wish list</button>
                        {% else %}
                        <button value="{{ product.id }}" name="wish" class="wish-form__input-btn-wish">Add to wish list</button>
                        {% endif %}
                    </form>
                </div>
                {% endif %}
                <div class="card-detail__description">
                    <p>{{ product.description }}</p>
                </div>
                {% if recommended_products %}
                <div class="card-detail__recommendations">
                    <h3>People who bought {{ product.name }}, also bought:</h3>
                    <div class="carousel owl-carousel owl-theme" id="carousel-header">
                        {% for item in recommended_products %}
                        <div class="carousel__item">
                            <img class="carousel__img" src="
                                {% if item.image %}
                                {{ item.image.url }}
                                {% else %}
                                {% static 'icons/no-image.png' %}
                                {% endif %}" alt="">
                            <div class="carousel__item-title">
                                <a class="link-lwc" href="{% url 'store:product-detail' slug=item.slug %}">
                                    <button class="carousel__item-title-header">
                                        {{ item.name }}
                                    </button>
                                </a>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endblock content %}

web/store/templates/store/product_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
{{ category }}
{% endblock title %}
{% block content %}
<div class="row">
    <div class="col-3">
        {% include "components/_sidebar.html" %}
    </div>
    <div class="col-9">
        <div class="cards-wrapper">
            {% for product in products %}
            <!-- card -->
            <div class="card">
                <!-- card__header -->
                <div class="card__header">
                    <div class="card__icon-btns">
                        <a href="{{ product.get_absolute_url }}">
                            <button class="card__icon-btn">
                                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="10" viewBox="0 0 18 10">
                                    <path d="M0 6V4h2v2zm0 4V8h2v2zm0-8V0h2v2zm4 4V4h14v2zm0 4V8h14v2zM4 0h14v2H4z" />
                                </svg>
                            </button>
                        </a>
                        {% if user.is_authenticated %}
                        <form method="POST">
                            {% csrf_token %}
                            {% if user.id in product.wished_by_users %}
                            <button style="" name="del" value="{{ product.id }}" class="card__icon-btn">
                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="19" viewBox="0 0 20 19">
                                    <path fill="red" d="M10.1 15.55l-.1.1-.1-.1C5.14 11.24 2 8.39 2 5.5 2 3.5 3.5 2 5.5 2c1.54 0 3.038.99 3.569 2.36h1.871C11.46 2.99 12.96 2 14.5 2c2.002 0 3.5 1.5 3.5 3.5 0 2.89-3.14 5.74-7.898 10.05zM14.5 0c-1.74 0-3.41.81-4.5 2.09C8.912.81 7.24 0 5.5 0 2.42 0 0 2.42 0 5.5c0 3.78 3.4 6.86 8.55 11.54L10 18.35l1.451-1.32C16.6 12.36 20 9.28 20 5.5 20 2.42 17.58 0 14.5 0z" />
                                </svg>
                            </button>
                            {% else %}
                            <button style="" name="wish" value="{{ product.id }}" class="card__icon-btn">
                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="19" viewBox="0 0 20 19">
                                    <path fill="black" d="M10.1 15.55l-.1.1-.1-.1C5.14 11.24 2 8.39 2 5.5 2 3.5 3.5 2 5.5 2c1.54 0 3.038.99 3.569 2.36h1.871C11.46 2.99 12.96 2 14.5 2c2.002 0 3.5 1.5 3.5 3.5 0 2.89-3.14 5.74-7.898 10.05zM14.5 0c-1.74 0-3.41.81-4.5 2.09C8.912.81 7.24 0 5.5 0 2.42 0 0 2.42 0 5.5c0 3.78 3.4 6.86 8.55 11.54L10 18.35l1.451-1.32C16.6 12.36 20 9.28 20 5.5 20 2.42 17.58 0 14.5 0z" />
                                </svg>
                            </button>
                            {% endif %}
                        </form>
                        {% endif %}
                    </div>
                </div>
                <!-- // card__header -->
                <div class="card__img">
                    <img src="
                    {% if product.image %}
                        {{ product.image.url }}
                    {% else %}
                        {% static 'icons/no-image.png' %}
                    {% endif %} " alt="" />
                </div>
                <a class="link-lwc" href="{{ product.get_absolute_url }}">
                    <h4 class="card__title">
                        {{ product.name }}
                    </h4>
                </a>
                <div class="card__rating">
                    {% include "components/_rating.html" %}
                    <div class="card__rating-value">{{ product.count_rates }}</div>
                </div>
                <div class="card__footer">
                    <div class="card__price">$ {{ product.price }}</div>
                    {% if user.is_authenticated %}
                    <form action="{% url 'cart:add-quick' product_id=product.id %}" method="POST">
                        {% csrf_token %}
                        {{ form }}
                        <button type="submit" class="card__cart">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20">
                                <path d="M6 16c1.1 0 1.999.9 1.999 2s-.9 2-2 2C4.9 20 4.01 19.1 4.01 18S4.9 16 6 16zM-.001 0H3.27l.939 2H19c.549 0 .997.45.997 1 0 .17-.039.34-.12.48l-3.58 6.49c-.338.62-.997 1.03-1.749 1.03H7.1l-.9 1.63-.029.12c0 .14.11.25.25.25h11.578v2H6c-1.1 0-2-.9-2-2 0-.35.089-.68.249-.96L5.6 9.59 2 2H0zM16 16c1.1 0 1.998.9 1.998 2S17.1 20 16 20s-1.989-.9-1.989-2 .89-2 1.99-2z" />
                            </svg>
                        </button>
                    </form>
                    {% endif %}
                </div>
            </div>
            <!-- // card -->
            {% endfor %}
        </div>
        {% include "components/_pagination.html" %}
    </div>
</div>
{% endblock content %}