web/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from api import views

router = DefaultRouter()

router.register('ratings',views.RatingViewSet, basename='ratings')
router.register('products', views.ProductsViewSet, basename='products')

urlpatterns = [
    path('', include(router.urls))
]

web/cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'
urlpatterns = [
    path('', views.CartView.as_view(), name='detail'),
    path('add/<int:product_id>/', views.cart_add, name='add'),
    path('add-quick/<int:product_id>/', views.cart_add_quick,
         name='add-quick'),
    path('remove/<int:product_id>/', views.cart_remove, name='remove')
]

web/users/urls.py
from django.urls import path
from users import views

app_name = 'users'
urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('update/profile', views.ProfileUpdateView.as_view(),
         name='update-profile'),
    path('update/password', views.PasswordUpdateView.as_view(),
         name='update-password'),
    path('signin/', views.SigninView.as_view(), name='signin'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('login/', views.logout_view, name='logout')
]

web/web/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('store.urls', namespace='store')),
    path('users/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payments/', include('payments.urls', namespace='payments'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        Online Store
        {% endblock title %}
    </title>
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %} ">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900&display=swap&subset=cyrillic-ext" rel="stylesheet">
</head>

<body>
    <header class="">
        <div class="container-fluid">
            <div class="header-top">
                {% if user.is_authenticated %}
                <a class="header-top__auth-link link-logout" href="{% url 'users:logout' %}">Logout</a>
                {% else %}
                <a class="header-top__auth-link link-sign" href="{% url 'users:signin' %}">Sign in</a>
                {% endif %}
                <h1>Online Store</h1>
                {% if user.is_authenticated %}
                <a class="header-top__auth-link link-cart 
                {% with total_items=cart|length %} 
                {% if cart|length > 0 %}
                cart
                {% endif %}
                {% endwith %}
                " href="{% url 'cart:detail' %}">Cart</a>
                {% else %}
                <a class="header-top__auth-link link-sign" href="{% url 'users:signup' %}">Sign up</a>
                {% endif %}
            </div>
            {% include "components/_navbar.html" %}
        </div>
    </header>
    <main>
        <div class="container-fluid">
            <div class="wrapper">
                {% block content %}
                {% endblock content %}
            </div>
        </div>
        </div>
    </main>
    <footer>
        <div class="footer">
            <p class="text-center copyright">Online Store &copy; Copyright {% now 'Y' %}</p>
        </div>
    </footer>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/carusel.js' %}"></script>
</body>

</html>

web/templates/index.html
{% extends "base.html" %}