web/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from api import views

router = DefaultRouter()

router.register('ratings',views.RatingViewSet, basename='ratings')
router.register('products', views.ProductsViewSet, basename='products')

urlpatterns = [
    path('', include(router.urls))
]

web/cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'
urlpatterns = [
    path('', views.CartView.as_view(), name='detail'),
    path('add/<int:product_id>/', views.cart_add, name='add'),
    path('add-quick/<int:product_id>/', views.cart_add_quick,
         name='add-quick'),
    path('remove/<int:product_id>/', views.cart_remove, name='remove')
]

web/orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'
urlpatterns = [
    path('create/', views.CreateOrderView.as_view(), name='create'),
    path('orderlist/', views.OrderListView.as_view(), name='list'),
    path('order/<int:id>/', views.OrderDetailView.as_view(), name='detail'),
    path('admin/order/<int:id>/', views.admin_order_detail,
         name='admin_order_detail'),
    path('admin/order/<int:id>/pdf/', views.admin_order_to_pdf,
         name='admin_order_pdf')
]

web/store/urls.py
from django.urls import path
from store import views

app_name = 'store'
urlpatterns = [
    path('', views.ProductListView.as_view(), name='productlist'),
    path('category/<str:slug>/', views.ProductCategoryListView.as_view(),
         name='productlist-by-category'),
    path('product/<str:slug>/', views.ProductDetailView.as_view(),
         name='product-detail'),
    path('wishlist/', views.WishListView.as_view(), name='wishlist'),
    path('recommendations/<int:user_id>/', views.RecommendationsView.as_view(),
         name='recommendations'),
    path('bestselling/', views.BestsellingView.as_view(), name='bestselling'),
    path('mostwished/', views.MostWishedView.as_view(), name='mostwished')
]

web/web/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('store.urls', namespace='store')),
    path('users/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payments/', include('payments.urls', namespace='payments'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/cart/forms.py
from django import forms


class CartAddForm(forms.Form):
    """Form for adding products to a cart."""

    quantity = forms.IntegerField(label='',
                                  widget=forms.NumberInput(
                                      attrs={
                                          'class': 'cart-form__input',
                                          'value':'1'
                                      }
                                  ))
    update = forms.BooleanField(required=False,
                                initial=False, widget=forms.HiddenInput)


class CartAddButton(forms.Form):
    """Form for adding products from a list page."""

    quantity = 1
    update = forms.BooleanField(required=False,
                                initial=False, widget=forms.HiddenInput)

web/cart/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.views.decorators.http import require_POST
from django.shortcuts import render, redirect, get_object_or_404
from store.models import Category, Product
from cart.cart import Cart
from cart.forms import CartAddForm, CartAddButton


class CartView(LoginRequiredMixin, View):
    """Cart detail view."""

    def get(self, request):
        cart = Cart(request)
        categories = Category.objects.all()
        for item in cart:
            item['update_quantity_form'] = CartAddForm(
                initial={'quantity': item['quantity'],
                         'update': True})
        context = {
            'cart': cart,
            'categories': categories
        }
        return render(request, 'cart/cart_detail.html', context)


@require_POST
@login_required
def cart_add(request, product_id):
    """Add item into a cart."""

    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddForm(request.POST)
    if form.is_valid():
        quantity = form.cleaned_data.get('quantity')
        update_quantity = form.cleaned_data.get('update')
        cart.add(product=product, quantity=quantity,
                 update_quantity=update_quantity)
        return redirect('cart:detail')


@require_POST
@login_required
def cart_add_quick(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddButton(request.POST)
    previous_page = request.META['HTTP_REFERER']
    if form.is_valid():
        quantity = form.quantity
        update_quantity = form.cleaned_data.get('update')
        cart.add(product=product, quantity=quantity,
                 update_quantity=update_quantity)

        return redirect(previous_page)


@login_required
def cart_remove(request, product_id):
    """Remove item from a cart."""

    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:detail')

web/cart/templates/cart/cart_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Cart
{% endblock title %}
{% block content %}
<div class="row">
    <div class="col-3">
        {% include "components/_sidebar.html" %}
    </div>
    <div class="col-9">
        <div class="cart-wrapper">
            <div class="cart-wrapper__title">
                <h2>Cart</h2>
                <hr>
            </div>
            <div class="cart-wrapper__body">
                <table class="body-cart">
                    <thead class="body-cart__threat">
                        <tr>
                            <th>Image</th>
                            <th>Product</th>
                            <th>Quantity</th>
                            <th>Remove</th>
                            <th>Unit price</th>
                            <th>Price</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in cart %}
                        {% with product=item.product %}
                        <tr>
                            <td>
                                <a href="{{ product.get_absolute_url }}">
                                    <img class="img-table" src="
                                    {% if product.image %}
                                    {{ product.image.url }}
                                    {% else %}
                                    {% static 'icons/no-image.png' %}
                                    {% endif %}">
                                </a> </td>
                            <td>{{ product.name }}</td>
                            <td>
                                <form action="{% url 'cart:add' product_id=product.id %}" method="post">
                                    {% csrf_token %}
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.update }} 
                                    <input class='cart-link' type="submit" value="Update"> 
                                </form>
                            </td>
                            <td><a href="{% url 'cart:remove' product_id=product.id%}" class="cart-link cart-link__remove">Remove</a></td>
                            <td class="num">${{ item.price }}</td>
                            <td class="num">${{ item.total_price }}</td>
                        </tr>
                        {% endwith %}
                        {% endfor %}
                        <tr class="total">
                            <td>Total</td>
                            <td colspan="4"></td>
                            <td class="num">${{ cart.get_total_price }}</td>
                        </tr>
                    </tbody>
                </table>
                <p class="text-right">
                    <a href="{% url  'store:productlist' %}" class="cart-link cart-link__continue">Continue shopping</a>
                    <a href="{% url 'orders:create' %}" class="cart-link cart-link__checkout">Checkout</a> </p>
            </div>
        </div>
    </div>
</div>
{% endblock content %}