web/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from api import views

router = DefaultRouter()

router.register('ratings',views.RatingViewSet, basename='ratings')
router.register('products', views.ProductsViewSet, basename='products')

urlpatterns = [
    path('', include(router.urls))
]

web/orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'
urlpatterns = [
    path('create/', views.CreateOrderView.as_view(), name='create'),
    path('orderlist/', views.OrderListView.as_view(), name='list'),
    path('order/<int:id>/', views.OrderDetailView.as_view(), name='detail'),
    path('admin/order/<int:id>/', views.admin_order_detail,
         name='admin_order_detail'),
    path('admin/order/<int:id>/pdf/', views.admin_order_to_pdf,
         name='admin_order_pdf')
]

web/store/urls.py
from django.urls import path
from store import views

app_name = 'store'
urlpatterns = [
    path('', views.ProductListView.as_view(), name='productlist'),
    path('category/<str:slug>/', views.ProductCategoryListView.as_view(),
         name='productlist-by-category'),
    path('product/<str:slug>/', views.ProductDetailView.as_view(),
         name='product-detail'),
    path('wishlist/', views.WishListView.as_view(), name='wishlist'),
    path('recommendations/<int:user_id>/', views.RecommendationsView.as_view(),
         name='recommendations'),
    path('bestselling/', views.BestsellingView.as_view(), name='bestselling'),
    path('mostwished/', views.MostWishedView.as_view(), name='mostwished')
]

web/users/urls.py
from django.urls import path
from users import views

app_name = 'users'
urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('update/profile', views.ProfileUpdateView.as_view(),
         name='update-profile'),
    path('update/password', views.PasswordUpdateView.as_view(),
         name='update-password'),
    path('signin/', views.SigninView.as_view(), name='signin'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('login/', views.logout_view, name='logout')
]

web/web/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('store.urls', namespace='store')),
    path('users/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payments/', include('payments.urls', namespace='payments'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/templates/components/_navbar.html
<nav class="header-nav">
    <div class="header-nav__categories">
        <a href="{% url 'store:productlist' %}" class="header-categories-link">
            <span class="header-categories-link__icon">
                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="12" viewBox="0 0 18 12">
                    <path d="M18 0v2H0V0zM0 5h18v2H0zm0 5h18v2H0z" />
                </svg>
            </span>
            <span class="header-categories-link__text">All Categories</span>
        </a>
    </div>
    <div class="header-nav__navbar">
        <a href="{% url 'store:mostwished' %}" class="header-nav__link">Most Wished</a>
        <a href="{% url 'store:bestselling' %}" class="header-nav__link">Bestselling</a>
        {% if user.is_authenticated %}
        <a href="{% url 'store:wishlist' %}" class="header-nav__link">Wish list</a>
        <a href="{% url 'store:recommendations' user_id=request.user.id %}" class="header-nav__link">Personal recommendations</a>
        {% endif %}
    </div>
    <!-- header-nav__select -->
    <div class="header-nav__select">
        <!-- ITEM -->
        <div class="header-nav__select-item">
            <!-- dropdown nav -->
            <div class="nav-dropdown">
                <a href="#" class="nav-dropdown__title">
                    Help
                    <div class="nav-dropdown__title-icon">
                        <svg xmlns="http://www.w3.org/2000/svg" width="8" height="5" viewBox="0 0 8 5">
                            <path d="M3.998 5L8 2.5V.104L3.998 2.62 0 0v2.5z" />
                        </svg>
                    </div>
                </a>
                <div class="nav-dropdown__dropdown">
                    <a href="#" class="nav-dropdown__dropdown-item">
                        F.A.Q.
                    </a>
                    <a href="#" class="nav-dropdown__dropdown-item">
                        Payment
                    </a>
                    <a href="#" class="nav-dropdown__dropdown-item">
                        Delivery
                    </a>
                </div>
            </div>
            <!-- // dropdown nav -->
        </div>
        <div class="header-nav__select-item">
            <!-- dropdown nav -->
            {% if user.is_authenticated %}
            <div class="nav-dropdown">
                <a href="#" class="nav-dropdown__title">
                    Profile
                    <div class="nav-dropdown__title-icon">
                        <svg xmlns="http://www.w3.org/2000/svg" width="8" height="5" viewBox="0 0 8 5">
                            <path d="M3.998 5L8 2.5V.104L3.998 2.62 0 0v2.5z" />
                        </svg>
                    </div>
                </a>
                <div class="nav-dropdown__dropdown">
                    <a href="{% url 'users:profile' %}" class="nav-dropdown__dropdown-item">
                        My Profile
                    </a>
                    <a href="{% url 'orders:list' %}" class="nav-dropdown__dropdown-item">
                        My Orders
                    </a>
                </div>
            </div>
            {% endif %}
            <!-- // dropdown nav -->
        </div>
</nav>

web/templates/components/_pagination.html
<div class="pagination">
    {% if products.paginator.num_pages > 1%}
    {% if products.has_previous %}
    <a class="pagination-action" href="?page={{ products.previous_page_number }}">&laquo;</a>
    {% endif %}
    {% for num in products.paginator.page_range %}
    {% if products.number == num %}
    <span class="pagination-number pagination-current">{{ num }}</span>
    {% elif num > products.number|add:'-3' and num < products.number|add:'3' %} <a class="pagination-number" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
        {% endfor %}
        {% if products.has_next %}
        <a class="pagination-action" href="?page={{ products.next_page_number }}">&raquo;</a>
        {% endif %}
        {% endif %}
</div>

web/templates/components/_rating.html
{% if product.get_rating > 0 and product.get_rating <= 0.5 %}
{% include "components/stars/05.html" %}
{% elif product.get_rating > 0.5 and product.get_rating <= 1.0 %}
{% include "components/stars/10.html" %}
{% elif product.get_rating > 1.0 and product.get_rating <= 1.5 %}
{% include "components/stars/15.html" %}
{% elif product.get_rating > 1.5 and product.get_rating <= 2.0 %}
{% include "components/stars/20.html" %}
{% elif product.get_rating > 2.0 and product.get_rating <= 2.5 %}
{% include "components/stars/25.html" %}
{% elif product.get_rating > 2.5 and product.get_rating <= 3.0 %}
{% include "components/stars/30.html" %}
{% elif product.get_rating > 3.0 and product.get_rating <= 3.5 %}
{% include "components/stars/35.html" %}
{% elif product.get_rating > 3.5 and product.get_rating <= 4.0 %}
{% include "components/stars/40.html" %}
{% elif product.get_rating > 4.0 and product.get_rating <= 4.5 %}
{% include "components/stars/45.html" %}
{% elif product.get_rating > 4.5 and product.get_rating <= 5.0 %}
{% include "components/stars/50.html" %}
{% else %}
{% include "components/stars/00.html" %}
{% endif %}

web/templates/components/_sidebar.html
<nav class="navigation">
    <ul class="navigation__list">
        {% for category in categories %}
        <a class="link-lwc" href="{{ category.get_absolute_url }}">
            <li class="navigation__item">
                <div class="navigation__item-icon">
                    <svg class="navigation__icon" xmlns="http://www.w3.org/2000/svg" width="22" height="20" viewBox="0 0 22 20">
                        <path d="M20 14H2V2h18zm0-14H2C.9 0 0 .9 0 2v12c0 1.1.9 2 2 2h7v2H7v2h8v-2h-2v-2h7c1.1 0 2-.9 2-2V2c0-1.1-.9-2-2-2z" />
                    </svg>
                </div>
                <div class="navigation__item-title">
                    {{ category.name }}
                </div>
                <div class="navigation__item-arrow">
                    <svg class="navigation__icon-arrow" xmlns="http://www.w3.org/2000/svg" width="6" height="10" viewBox="0 0 6 10">
                        <path d="M6.001 5.002L2.999 0H.126l3.018 5.002L0 10h3z" />
                    </svg>
                </div>
            </li>
        </a>
        {% endfor %}
    </ul>
</nav>

web/templates/components/navbar.html
<nav class="header-nav">
    <div class="header-nav__categories">
        <a href="#" class="header-categories-link">
            <span class="header-categories-link__icon">
                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="12" viewBox="0 0 18 12">
                    <path d="M18 0v2H0V0zM0 5h18v2H0zm0 5h18v2H0z" />
                </svg>
            </span>
            <span class="header-categories-link__text">All Categories</span>
        </a>
    </div>
    <div class="header-nav__navbar">
        <a href="#" class="header-nav__link">Super Deals</a>
        <a href="#" class="header-nav__link">Featured Brands</a>
        <a href="#" class="header-nav__link">Collections</a>
        <a href="#" class="header-nav__link">Bestselling</a>
    </div>
    <!-- header-nav__select -->
    <div class="header-nav__select">
        <!-- ITEM -->
        <div class="header-nav__select-item">
            <!-- dropdown nav -->
            <div class="nav-dropdown">
                <a href="#" class="nav-dropdown__title">
                    Help
                    <div class="nav-dropdown__title-icon">
                        <svg xmlns="http://www.w3.org/2000/svg" width="8" height="5" viewBox="0 0 8 5">
                            <path d="M3.998 5L8 2.5V.104L3.998 2.62 0 0v2.5z" />
                        </svg>
                    </div>
                </a>
                <div class="nav-dropdown__dropdown">
                    <a href="#" class="nav-dropdown__dropdown-item">
                        F.A.Q.
                    </a>
                    <a href="#" class="nav-dropdown__dropdown-item">
                        Payment
                    </a>
                    <a href="#" class="nav-dropdown__dropdown-item">
                        Delivery
                    </a>
                </div>
            </div>
            <!-- // dropdown nav -->
        </div>
        <div class="header-nav__select-item">
            <!-- dropdown nav -->
            <div class="nav-dropdown">
                <a href="#" class="nav-dropdown__title">
                    Profile
                    <div class="nav-dropdown__title-icon">
                        <svg xmlns="http://www.w3.org/2000/svg" width="8" height="5" viewBox="0 0 8 5">
                            <path d="M3.998 5L8 2.5V.104L3.998 2.62 0 0v2.5z" />
                        </svg>
                    </div>
                </a>
                <div class="nav-dropdown__dropdown">
                    <a href="#" class="nav-dropdown__dropdown-item">
                        USD
                    </a>
                    <a href="#" class="nav-dropdown__dropdown-item">
                        RUR
                    </a>
                    <a href="#" class="nav-dropdown__dropdown-item">
                        UAH
                    </a>
                </div>
            </div>
            <!-- // dropdown nav -->
        </div>
</nav>